#!/bin/env python

import yaml
import sys

from src import astu
from src import backup
from src import repository


def main():
    a = astu.Astu()
    a.parse(sys.argv[1:])
    a.run()


if __name__ == '__main__':
    main()



